cells:
  location: world, -1651.500, 162.500, -2470.500
  lines:
  - '&eCells'
  - '&6&lCLICK'
clegendary:
  location: world, -1620.500, 163.200, -2471.500
  lines:
  - '&6» &eCaja Mistica &6«'
  - ''
  - '&6&lCLICK'
crare:
  location: world, -1619.636, 163.200, -2475.446
  lines:
  - '&4» &cCaja Antigua &4«'
  - ''
  - '&6&lCLICK'
ccommon:
  location: world, -1619.707, 163.200, -2467.586
  lines:
  - '&5» &dCaja de Ventajas &5«'
  - ''
  - '&6&lCLICK'
m1:
  location: mines, 2493.500, 103.700, -13.500
  lines:
  - '&eSell All'
  - '&6&lCLICK'
m2:
  location: mines, 2493.500, 103.700, 486.500
  lines:
  - '&eSell All'
  - '&6&lCLICK'
m3:
  location: mines, 2493.500, 103.700, 986.500
  lines:
  - '&eSell All'
  - '&6&lCLICK'
m4:
  location: mines, 2493.500, 103.700, 1486.500
  lines:
  - '&eSell All'
  - '&6&lCLICK'
m5:
  location: mines, 487.500, 103.700, 13.500
  lines:
  - '&eSell All'
  - '&6&lCLICK'
m6:
  location: mines, 487.500, 103.700, 513.500
  lines:
  - '&eSell All'
  - '&6&lCLICK'
m7:
  location: mines, 487.500, 103.700, 1013.500
  lines:
  - '&eSell All'
  - '&6&lCLICK'
m8:
  location: mines, 487.500, 103.700, 1513.500
  lines:
  - '&eSell All'
  - '&6&lCLICK'
treward:
Ice Merchant'  location: world, -1646.500, 161.200, -2478.500
  lines:
  - '&eCofre del tesoro'
  - '&6&lCLICK'
cvvote:
  location: world, -1623.500, 163.200, -2462.500
  lines:
  - '&2» &aCaja Vote &2«'
  - ''
  - '&6&lCLICK'
ice:
  location: world, -1640.500, 117.500, -2507.500
  lines:
  - '&eComerciante de hielo '
  - '&6&lCLICK'
shop:
  location: world, -1670.700, 158.500, -2465.500
  lines:
  - '&eTienda'
  - '&6&lCLICK'
holo:
  location: world, -1636.500, 163.000, -2467.500
  lines:
  - '&e❖ &6&lPRISON &e❖'
  - '&7&oDisfruta tratando de escapar!'
  - ''
  - '&fen la prisión el modo de juego será'
  - '&fcapaz de crear su propia celda y clasificación'
  - '&fpor la mineria para liberarse algun dia!'
  - ''
  - '&epulsar &d[F] &eclave para abrir su angular!'
m9:
  location: mines, 1009.500, 103.700, 17.500
  lines:
  - '&eVender Todo'
  - '&6&lCLICK'
m10:
  location: mines, 1009.500, 103.700, 517.500
  lines:
  - '&eVender Todo'
  - '&6&lCLICK'
m11:
  location: mines, 1009.500, 103.700, 1017.500
  lines:
  - '&eVender Todo'
  - '&6&lCLICK'
m12:
  location: mines, 1009.500, 103.700, 1517.500
  lines:
  - '&eVender Todo'
  - '&6&lCLICK'
m13:
  location: mines, 2015.500, 103.700, 9.500
  lines:
  - '&eVender Todo'
  - '&6&lCLICK'
m101:
  location: mines, 2015.500, 103.700, 509.500
  lines:
  - '&eVender Todo'
  - '&6&lCLICK'
character:
  location: world, -1644.500, 161.500, -2457.500
  lines:
  - '&eMenu de Personajes'
  - '&6&lCLICK'
strongbox:
  location: world, -1648.500, 161.200, -2456.500
  lines:
  - '&eCaja Fuerte'
  - '&6&lCLICK'
pvp:
  location: world, -1688.500, 154.668, -2470.500
  lines:
  - '&eBienvenido a la &6&lGlaciacion de Yrim!'
  - ''
  - '&fDebe ser &7[B4] &fgrado o'
  - '&fmas alto para minar hielo empaquetado&f!'
pvp2:
  location: world, -1720.500, 141.000, -2491.500
  lines:
  - '&c&lPVP HABILITADO AQUI ABAJO'
  - ''
  - '&fInventario se cae en la muerte'
icepacked:
  location: world, -1717.500, 142.000, -2488.500
  lines:
  - '&fEstado: &aMineable'
  - '&fCada: &b30 minute(s)'
icepacked2:
  location: world, -1717.500, 142.500, -2494.500
  lines:
  - '&eVende tu hielo empaquetado en el'
  - '&eComerciante de hielo OESTE desde aqui.'
  - ''
  - '&61x Hielo envasado &f= &e$5,000'
coinflip:
  location: world, -1693.500, 155.500, -2443.500
  lines:
  - '&eTeletransportador '
  - '&6&lCLICK'
enchanting:
  location: world, -1693.500, 155.500, -2459.500
  lines:
  - '&eEncantador'
  - '&6&lCLICK'
petsy:
  location: world, -1695.500, 155.500, -2455.500
  lines:
  - '&eMascotas'
  - '&6&lCLICK'
banky:
  location: world, -1695.500, 155.500, -2447.500
  lines:
  - '&eBanco'
  - '&6&lCLICK'
m111:
  location: mines, 2015.500, 103.700, 1009.500
  lines:
  - '&eVender Todo'
  - '&6&lCLICK'
m222:
  location: mines, 2015.500, 103.700, 1509.500
  lines:
  - '&eVender Todo'
  - '&6&lCLICK'
m333:
  location: mines, 1358.500, 145.700, -150.500
  lines:
  - '&eVender Todo'
  - '&6&lCLICK'
m444:
  location: mines, 1358.500, 145.700, 349.500
  lines:
  - '&eVender Todo'
  - '&6&lCLICK'
m555:
  location: mines, 1358.500, 145.700, 849.500
  lines:
  - '&eVender Todo'
  - '&6&lCLICK'
m1123:
Ice Merchant'  location: mines, 1358.500, 145.700, 1349.500
  lines:
  - '&eVender Todo'
  - '&6&lCLICK'
enderchestspawn:
  location: world, -1623.500, 162.000, -2480.500
  lines:
  - '&eEnder pecho'
  - '&6&lCLICK'
gang:
  location: world, -1697.500, 155.500, -2451.500
  lines:
  - '&ePandilla'
  - '&6&lCLICK'
yrimh:
  location: world, -1695.500, 148.400, -2496.500
  lines:
  - '&6&lVENTA RAPIDA DE ODIN'
  - '&c[Requiere el renacimiento de Odin]'
  - '&fUsa el Mercante al sur de aqui'
  - '&fsi el renacimiento de Odin no se completa'
  - '&eComerviante de Hielo'

