join commands:
  # The id for this command is "exampleCommand1"
  # There is no use for this right now so you can set it to anything
  # Just make sure none of them are the same
  exampleCommand1:
    # The command to run
    # Do not put a /
    # You can run it as the player if you add [PLAYER] to the beggining
    # You can run it as the player with all permissions if you add [OP] to the beginning
    # You can run it as a bungee player if you add [PBUNGEE] to the beginning (and if JoinCommandsBungee is installed on your BungeeCord Proxy)
    # You can run it as the bungee console if you add [CBUNGEE] to the beginning (and if JoinCommandsBungee is installed on your BungeeCord Proxy)
    command: 'bc &6&lWELCOME &8┃ &fWelcome &e&n{player}&f to &6&lPrison&f! &7(#{UNIQUE}).'
    
    # How long to wait after the player has joined
    # This is in ticks, so 20 = 1 second
    delay: 20
    
    # Should this commmand require a permission to execute?
    # Set this to '' to not use a permission
    permission: ''
    
    # Should this command only execute the first time a player joins?
    # Set this to false to execute on every join
    first join only: true
    
  #exampleCommand2:
  #  command: '[PLAYER]suicide'
  #  delay: 40
  #  permission: 'jc.we.hate.you'
  #  first join only: false
  
  #examplecommand3;
  #  command: '[PBUNGEE]server factions'
  #  delay: 10
  #  permission 'server.auto.join.factions'
  #  first join only: false
  exampleCoewmmgfand1:
    # The command to run
    # Do not put a /
    # You can run it as the player if you add [PLAYER] to the beggining
    # You can run it as the player with all permissions if you add [OP] to the beginning
    # You can run it as a bungee player if you add [PBUNGEE] to the beginning (and if JoinCommandsBungee is installed on your BungeeCord Proxy)
    # You can run it as the bungee console if you add [CBUNGEE] to the beginning (and if JoinCommandsBungee is installed on your BungeeCord Proxy)
    command: 'minecraft:tp {player} -1632 159 -2472 51 -9'
    
    # How long to wait after the player has joined
    # This is in ticks, so 20 = 1 second
    delay: 0
    
    # Should this commmand require a permission to execute?
    # Set this to '' to not use a permission
    permission: ''
    
    # Should this command only execute the first time a player joins?
    # Set this to false to execute on every join
    first join only: false
  examwererfpleCoewmmand1:
    # The command to run
    # Do not put a /
    # You can run it as the player if you add [PLAYER] to the beggining
    # You can run it as the player with all permissions if you add [OP] to the beginning
    # You can run it as a bungee player if you add [PBUNGEE] to the beginning (and if JoinCommandsBungee is installed on your BungeeCord Proxy)
    # You can run it as the bungee console if you add [CBUNGEE] to the beginning (and if JoinCommandsBungee is installed on your BungeeCord Proxy)
    command: 'give {player} diamond_pickaxe 1 EFFICIENCY:5 UNBREAKING:15 lore:&7|&6&lINFORMATION:|__&e&l*_&fOwner:_&b{player}|&7|&e&nRight-click_to_open!'
    
    # How long to wait after the player has joined
    # This is in ticks, so 20 = 1 second
    delay: 1
    
    # Should this commmand require a permission to execute?
    # Set this to '' to not use a permission
    permission: ''
    
    # Should this command only execute the first time a player joins?
    # Set this to false to execute on every join
    first join only: true
  examdgsdfdasadfaqse121mand1:
    # The command to run
    # Do not put a /
    # You can run it as the player if you add [PLAYER] to the beggining
    # You can run it as the player with all permissions if you add [OP] to the beginning
    # You can run it as a bungee player if you add [PBUNGEE] to the beginning (and if JoinCommandsBungee is installed on your BungeeCord Proxy)
    # You can run it as the bungee console if you add [CBUNGEE] to the beginning (and if JoinCommandsBungee is installed on your BungeeCord Proxy)
    command: 'pex group Member user add {player}'
    
    # How long to wait after the player has joined
    # This is in ticks, so 20 = 1 second
    delay: 1
    
    # Should this commmand require a permission to execute?
    # Set this to '' to not use a permission
    permission: ''
    
    # Should this command only execute the first time a player joins?
    # Set this to false to execute on every join
    first join only: true
  e32434dffd3333:
    # The command to run
    # Do not put a /
    # You can run it as the player if you add [PLAYER] to the beggining
    # You can run it as the player with all permissions if you add [OP] to the beginning
    # You can run it as a bungee player if you add [PBUNGEE] to the beginning (and if JoinCommandsBungee is installed on your BungeeCord Proxy)
    # You can run it as the bungee console if you add [CBUNGEE] to the beginning (and if JoinCommandsBungee is installed on your BungeeCord Proxy)
    command: 'pex group A2 user add {player}'
    
    # How long to wait after the player has joined
    # This is in ticks, so 20 = 1 second
    delay: 1
    
    # Should this commmand require a permission to execute?
    # Set this to '' to not use a permission
    permission: ''
    
    # Should this command only execute the first time a player joins?
    # Set this to false to execute on every join
    first join only: true