# PlayerWarps by Olzie-12
# https://www.spigotmc.org/resources/player-warps-1-8-1-13.66692/
# We also have a discord server for help: https://discord.gg/bAHuRJq
# Also if you find any bugs be happy to report them i will fix them :)
# Made with love

# DO NOT TOUCH THIS!
config-version: 55

settings:
  # very useful to tell if there are any memory leaks or if the author needs
  # information.
  debug: false
  # notifies you if there is a update (Only people with pw.admin.update can see this when they join)
  notify-update: false
  # Plugin metrics, this is very useful for the author to
  # see information about the server. Please keep it enabled,
  # it makes me more encouraged to make plugins like this.
  # YOU WILL NEED TO RESTART THE SERVER!
  metrics: true
  # Want to disable the sponsor message that is shown in the console?
  sponsor-message: false
  # This is the main command for the plugin. YOU WILL NEED TO RESTART THE SERVER!
  main-command: sdgdf213sg
  # Extra aliases for the main command. YOU WILL NEED RESTART THE SERVER!
  command-aliases:
  - 'dsfgfdafs'

  # Should database information be displayed in the tab-complete? For example warp-names.
  tab-complete: true


  # What order should the warps be listed?
  # options:
  # - VISITS = The order will be from the warp most visits.
  # - ALPHABETICAL = The order will be from alphabetical order.
  # - WHEN_CREATED = The order will be when the warp was created.
  # - RATES = The order will be from the most rates.
  # - RATES_AVERAGE = The order will be from the highest average rates.
  order: VISITS

  sub-commands:
    # If you disable any of these, it will just show the help menu.
    desc-command: true
    list-command: true
    # If the open command is disabled, the only way to open the MENU is to actually type /pwarp. (Only if you have it overridden in gui.yml).
    # If you have this command disabled, and /pwarp is not overridden in the gui.yml. No one will be able to use the GUI.
    # If you wish to disable the GUI just turn it off in gui.yml. Turning the GUI off, also disables the open command.
    open-command: true
    # Yes, i know. Someone wanted for these to be disabled. Don't ask.
    remove-command: false
    set-command: true
    teleport-command: true
    amount-command: false
    icon-command: false
    category-command: false
    rate-command: true
    password-command: false
    lock-command: true
    cost-command: true
    reset-command: true
    rename-command: false
    setowner-command: false

    # Here the sub command syntax's please know that you cannot have spaces in these otherwise you will break everything
    desc-command-name: desc
    list-command-name: list
    open-command-name: open
    remove-command-name: remove
    set-command-name: set
    amount-command-name: amount
    icon-command-name: icon
    category-command-name: category
    rate-command-name: rate
    password-command-name: password
    lock-command-name: lock
    cost-command-name: cost
    reset-command-name: reset
    rename-command-name: rename
    setowner-command-name: setowner

  #####################################################################################
  #                                                                                   #
  #      WARNING BEFORE YOU USE THIS database FEATURE, THIS FEATURE IS IN BETA!       #
  #      DO NOT COMPLAIN SAYING THAT IT IS NOT WORKING, IF YOU HAVE ANY COMPLAINTS    #
  #      PLEASE REPORT IT IN THE DISCORD SERVER (https://discord.gg/bAHuRJq)!!        #
  #      I WOULD HIGHLY SUGGEST THAT YOU TEST THIS ON A TEST SERVER! THANKS <3        #
  #                                                                                   #
  ######################################################################################

  # With SQL Support PlayerWarps will download another plugin called "PlayerWarps Bungee Extension". Don't worry about it okay :)
  # Never do /pwarp reload if you changed the database details. It will mess everything, if you wish to change it, change it then restart the server.
  # That also means do not reload the plugin with plugman, because the way the database syncs up with "PlayerWarps Bungee Extension" it will mess everything, just please simply restart the server.
  # This also means if you have just enabled/disabled it please restart the server.

  # WARNING: Because I'm only working with MySQL and Bungeecord. It is very limited. Meaning it can be slow due to MySQL updates
  # There is also a big limitation that removes some awesome features that PlayerWarps gives like:
  # Checking if the warp is safe

  # I cannot do anything about this, its just how spigot works. Sorry :(

  database:
    # Please enter the server name on your bungee network, otherwise the plugin will not be able to redirect you to that server.
    # If you don't want to setup this database as a bungee network, please leave this blank.
    server-name: ''


    sql:
      # Should SQL be enabled?
      enabled: false
      # If enabled PlayerWarps needs to be connected to the SQL database, please enter your details.
      # I am not responsible for any leakage of these details. (If an admin accesses it etc..)

      # What is the hostname?
      hostname: spigotmc.org
      # What is the port? Most database ports are 3306.
      port: 3306
      # What is your database name?
      database: PlayerWarps
      # What is your database username?
      username: root
      # What is your database password?
      password: root

    # How often should the GUI refresh in every server? If the time is low the more lag the plugin could produce. This is in seconds.
    refresh-time: 60

  icon:
    # Set the icon as a item in a player's hand. If this is disabled the player will need to enter the item name manually.
    icon-set-item-in-hand: true
    # What are the blacklisted items that players cannot set to their warp icon to?
    blacklisted-items:
    - 'AIR'

  set:
    # Should there be a confirmation before setting a warp?
    confirmation: false
    # How many seconds, show the confirmation expire for the warp. This means how many seconds they have to wait
    # to set to a warp. Recommended is 3
    confirmation-expire-time: 3
    # the amount of characters a warp name can have.
    max-warp-name-chars: 10
    # Blacklist any names from anyone setting a playerwarp called that.
    blacklisted-names:
    - 'olzieisbad'
    # What is the cooldown for setting a warp? Set this to -1 to disable.
    cooldown: 5

    economy:
      # This is how much they will need to set  a warp, otherwise if they don't have that it will not set the warp and send the message
      # in lang.yml. Make sure you have an economy plugin and vault supports that economy plugin!
      # Set this to -1 to disable.
      set-price: -1
      # Here you can choose specific ranks that the price they need to pay, if you have not put a rank there the payment will be payment will be above.
      # WARNING This will not work if you're using the default Bukkit Permissions system due to vault not supporting groups.
      set-ranks-pay:
        # THe rank VIP only needs to pay $1
        vip: -1
        # The rank MVP does not need to pay
        MVP: -1

    # Should players not be able to set warps in these worlds?
    disabled-worlds:
    - 'world_nether'

  # The remove section.
  remove:
    # Should there be a confirmation before removing a warp?
    confirmation: false
    # How many seconds, show the confirmation expire for the warp. This means how many seconds they have to wait
    # to remove to a warp. Recommended is 3
    confirmation-expire-time: 3

    # Should a player's warp's get removed because they are offline for x amount of days?
    # THIS IS NOT RECOMMEND TO BE ENABLED DUE TO THIS IS RISK OF WARPS BEING DELETED!

    purge:
      # Should it be enabled?
      enabled: false
      # How many days should a player be offline for?
      time: 30

      # Should these players not get removed if they are offline for x amount of days? Please put UUIDS otherwise it will not work.
      # here is a uuid converter (https://mcuuid.net/), make sure to get the "full uuid" not the "trimmed uuid".
      restricted-players:
      - '5ca251ab-589d-4f04-8f0c-28404d0686b0'

    # Should a warp be deleted after x amount of days when it was set even though the player has logged on?
    # THIS IS NOT RECOMMEND TO BE ENABLED DUE TO THIS IS RISK OF WARPS BEING DELETED!
    remove-days:
      # Should it be enabled?
      enabled: false
      # How many days after the warp has been set should the warp be deleted?
      time: 30

      # Should these players not get removed if they are offline for x amount of days? Please put UUIDS otherwise it will not work.
      # here is a uuid converter (https://mcuuid.net/), make sure to get the "full uuid" not the "trimmed uuid".
      restricted-players:
      - '5ca251ab-589d-4f04-8f0c-28404d0686b0'


  # The teleport section.
  teleport:
    # Should we enable the unsafe-block feature, meaning that a player can set a warp to trap players and kill them innocently.
    unsafe-block: true
    # This is how many blocks down it checks.
    blocks-down-check: 1
    # The plugin will check before they warp to see if the warp is unsafe, these are the blocks that get checked below the warp.
    # Valid material names: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    unsafe-blocks:
    - 'STATIONARY_LAVA'
    - 'AIR'
    - 'MAGMA'
    # How many seconds, show the timer expire for the unsafe warp. This means how many seconds they have to click
    # the warp again to teleport to an unsafe warp. Recommended is 3. Set to -1 to disable
    time-expire-unsafe: 3
    # Should the vists only be counted once per player, or be counted every time a player teleports to it.  This is HIGHLY recommended as true so players cannot farm it.
    protect-boost-visits: true
    # How much time does the player need to stay still, till they get teleported to a warp? Set this to -1 to disable.
    # You can bypass this by giving the permission 'pw.delay.bypass'
    teleport-wait: 3
    # What is the cooldown for teleporting to a warp? Set this to -1 to disable.
    cooldown: 5
    # Do you only want specific warps to have a cooldown?
    specific-warps: false
    # If the above option is true, what are the names of the warps?
    specific-warps-list:
    - ''

    # What are the commands that should be executed upon teleportation?
    # [server] means the command is executed as the console
    # [player] means the command is executed as the player
    commands:
    - ''

    # For the particles please use this! https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
    # For the sounds please use this! https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    particles:
      # What particle should be shown when they are teleporting to a playerwarp? Set this to false to disable.
      # YOU WILL NEED TO CHANGE THE PARTICLE IF YOU ARE ON A DIFFERENT VERSION!
      # PLEASE DO NOT SET THIS TO TRUE! IT CAN EITHER BE FALSE OR A PARTICLE NAME
      particle-teleport: false
      # How many particles should there be?
      particle-count: 2
      # Should the player see the particle, or should everyone see the particle? This is recommended as just the player.
      particle-only-player: true

    sounds:
      # What sound should be played when they are teleporting to a playerwarp? Set this to false to disable.
      # YOU WILL NEED TO CHANGE THE SOUND IF YOU ARE ON A DIFFERENT VERSION!
      # PLEASE DO NOT SET THIS TO TRUE! IT CAN EITHER BE FALSE OR A SOUND NAME
      sound-teleport: true
      # What should the volume be when the sound is played?
      volume-teleport: 1.0
      # What should the pitch be when the sound is played?
      pitch-teleport: 1.0



    economy:
      # This is how much they will need to teleport to a warp, otherwise if they don't have that it they wont teleport to the warp and send the message
      # in lang.yml. Make sure you have an economy plugin and vault supports that economy plugin!
      # Set this to -1 to disable.
      teleport-price: -1
      # Here you can choose specific ranks that the price they need to pay, if you have not put a rank there the payment will be payment will be above.
      # WARNING This will not work if you're using the default Bukkit Permissions system due to vault not supporting groups.
      teleport-ranks-pay:
        # THe rank VIP only needs to pay $1
        vip: -1
        # The rank MVP does not need to pay
        MVP: -1
      # Should the money be given to the owner of the warp?
      give-to-owner: true



  desc:
    # the amount of characters a desc can have.
    max-warp-desc-chars: 50
    # The description will automatically go onto the next line if there is x amount of characters on that line
    # How many characters should a description be par line?
    characters-per-line: 15


  rate:
    # What is the maximum amount a player can rate for a warp?
    max-rates: 5
    # Can a player rate their own warp?
    owner-rate: false

  backups:
    # Should backups be enabled? I highly recommenced you keep this enabled.
    enabled: false
    # What are the maximum amount of backups allowed in the backup folder? Set this to -1 to keep unlimited backups
    maximum: 10

# Should PlayerWarps be able to convert data from other plugins?
converters:
  MySQL:
    # if this is enabled, this will convert data from the data.yml to mysql.
    # please restart the server for this conversion to happen.
    enabled: false
  WelcomeWarpSign:
    # if this is enabled, this will convert data from Welcome Warp Sign to PlayerWarps.
    # Please restart the server for this conversion to happen.
    enabled: false

plugins:
  # plotsquared support will allow players to only set warps
  # in their plot. The permission for admins to bypass is 'pw.admin.bypass'.
  plotsquared:
    # Do you want to enable plotsquared support?
    # You need plotsquared installed for this to work!
    enabled: true
    # Should the warp be created when a plot is created?
    create: true
    # Should the warp get deleted once the plot is deleted?
    delete: true
    lang:
      not-in-plot: '%prefix% &cSorry you can''t set a warp here, &cYou aren''t on a plot!'
      dont-own-plot: '%prefix% &cSorry you can''t set a warp here, because you dont own this plot!'

  # worldguard support will allow players to only set warps outside
  # of regions. The permission for admins to bypass is 'pw.admin.bypass'.
  worldguard:
    # Do you want to enable worldguard support?
    # You need worldguard installed for this to work!
    enabled: true
    lang:
      in-region: '%prefix% &cSorry you can''t set a warp here, because you are in a region!'

  askyblock:
    # Do you want to enable askyblock support?
    # You need askyblock installed for this to work!
    enabled: false
    # Should the warp be created when a island is created?
    create: false
    # Should the warp get deleted once the island is deleted?
    delete: true
    lang:
      not-in-island: '%prefix% &cSorry you can''t set a warp here, &cYou aren''t on a island!'
      dont-own-island: '%prefix% &cSorry you can''t set a warp here, because you don''t own this island.'

  griefprevention:
    # Do you want to enable griefprevention support?
    # You need griefprevention installed for this to work!
    enabled: false
    # Should the warp be created when a claim is created?
    create: false
    # Should the warp get deleted once the claim is deleted?
    delete: true
    lang:
      not-in-claim: '%prefix% &cSorry you can''t set a warp here, &cYou aren''t in a claim!'
      dont-own-claim: '%prefix% &cSorry you can''t set a warp here, because you don''t own this claim.'

  fabledskyblock:
    # Do you want to enable fabledskyblock support?
    # You need fabledskyblock installed for this to work!
    enabled: false
    # Should the warp be created when a island is created?
    create: false
    # Should the warp get deleted once the island is deleted?
    delete: true
    lang:
      not-in-island: '%prefix% &cSorry you can''t set a warp here, &cYou aren''t on a island!'
      dont-own-island: '%prefix% &cSorry you can''t set a warp here, because you don''t own this island.'

  lands:
    # Do you want to enable lands support?
    # You need lands installed for this to work!
    enabled: false
    # Should the warp be created when a land is created?
    create: false
    # Should the warp get deleted once the land is deleted?
    delete: true
    lang:
      not-in-land: '%prefix% &cSorry you can''t set a warp here, &cYou aren''t on a land'
      dont-own-land: '%prefix% &cSorry you can''t set a warp here, because you don''t own this land.'

  simpleskyblock:
    # Do you want to enable simpleskyblock support?
    # You need simpleskyblock installed for this to work!
    enabled: false
    lang:
      not-in-island: '%prefix% &cSorry you can''t set a warp here, &cYou aren''t on a island!'
      dont-own-island: '%prefix% &cSorry you can''t set a warp here, because you don''t own this island.'

  factions:
    # Do you want to enable factions support?
    # You need factions installed for this to work!
    enabled: false
    # Should the warp get deleted once the faction is deleted?
    delete: true
    lang:
      not-in-claim: '%prefix% &cSorry you can''t set a warp here, &cYou aren''t in a claim!'
      dont-own-claim: '%prefix% &cSorry you can''t set a warp here, because you don''t own this claim.'

  factionsuuid:
    # Do you want to enable factionsuuid support?
    # You need factionsuuid installed for this to work!
    enabled: false
    # Should the warp get deleted once the faction is deleted?
    delete: true
    lang:
      not-in-claim: '%prefix% &cSorry you can''t set a warp here, &cYou aren''t in a claim!'
      dont-own-claim: '%prefix% &cSorry you can''t set a warp here, because you don''t own this claim.'
