secondInv:
  TitleMain: '&eMix-Color'
  Items:
    Obfuscated: '171:1'
    Bold: '171:2'
    Strikethrough: '171:3'
    Underline: '171:4'
    Italic: '171:5'
  Title:
    Obfuscated: '&6Obfuscated'
    Bold: '&6Bold'
    Strikethrough: '&6Strikethrough'
    Underline: '&6Underline'
    Italic: '&6Italic'
  Lore:
    Obfuscated: '&eObfuscate your ChatColor!'
    Bold: '&eMix your ChatColor with Bold'
    Strikethrough: '&eStrikethrough your ChatColor!'
    Underline: '&eMix your ChatColor with Underline!'
    Italic: '&eMix your ChatColor with Italic!'
  Format:
    Obfuscated: '&k'
    Bold: '&l'
    Strikethrough: '&m'
    Underline: '&n'
    Italic: '&o'
ResetItem:
  COLOR: '&r'
  ColorChanged: '&aYou have changed your ChatColor back to &enormal &a!'
  NameColorChanged: '&aYou have changed your NameColor back to &enormal &a!'
  TabColorChanged: '&aYou have changed your TabColor back to &enormal &a!'
  ID: '20'
  Title:
    Color: '&4Click to reset your ChatColor!'
    NameColor: '&4Click to reset your NameColor!'
    TabColor: '&4Click to reset your TabColor!'
  Lore:
    Color: Change your ChatColor back to normal
    NameColor: Change your NameColor back to normal
    TabColor: Change your TabColor back to normal
ErrorMode:
  Active: true
Items:
  BLUE: '35:3'
  BLACK: '35:15'
  DARK_BLUE: '35:11'
  DARK_GREEN: '35:13'
  DARK_AQUA: '35:9'
  DARK_RED: '35:14'
  DARK_PURPLE: '35:10'
  GOLD: '171:4'
  GRAY: '35:8'
  DARK_GRAY: '35:7'
  GREEN: '35:5'
  AQUA: '171:9'
  RED: '171:14'
  LIGHT_PURPLE: '35:2'
  YELLOW: '35:4'
  WHITE: '35:0'
NameColorItems:
  BLUE: '35:3'
  BLACK: '35:15'
  DARK_BLUE: '35:11'
  DARK_GREEN: '35:13'
  DARK_AQUA: '35:9'
  DARK_RED: '35:14'
  DARK_PURPLE: '35:10'
  GOLD: '171:4'
  GRAY: '35:8'
  DARK_GRAY: '35:7'
  GREEN: '35:5'
  AQUA: '171:9'
  RED: '171:14'
  LIGHT_PURPLE: '35:2'
  YELLOW: '35:4'
  WHITE: '35:0'
  rainbow: 384
TabColorItems:
  BLUE: '35:3'
  BLACK: '35:15'
  DARK_BLUE: '35:11'
  DARK_GREEN: '35:13'
  DARK_AQUA: '35:9'
  DARK_RED: '35:14'
  DARK_PURPLE: '35:10'
  GOLD: '171:4'
  GRAY: '35:8'
  DARK_GRAY: '35:7'
  GREEN: '35:5'
  AQUA: '171:9'
  RED: '171:14'
  LIGHT_PURPLE: '35:2'
  YELLOW: '35:4'
  WHITE: '35:0'
  rainbow: 384
Message:
  test: this is just a test
  Bla: another test
  noperm: '&cYou don''t have permissions to use this Command!'
  ColorInv: '&6Choose your ChatColor:'
  color_changed:
    Normal: '&6You changed your ChatColor to%colorID% %colorName% &6!'
    Mixed: '&6You changed your ChatColor to%colorID% %colorName% &6mixed with %colorMixed%&6!'
  inv_title:
    BLUE: '&9blue'
    BLACK: '&0black'
    DARK_BLUE: '&1dark blue'
    DARK_GREEN: '&2dark green'
    DARK_AQUA: '&3dark aqua'
    DARK_RED: '&4dark red'
    DARK_PURPLE: '&5dark purple'
    GOLD: '&6gold'
    GRAY: '&7gray'
    DARK_GRAY: '&8dark gray'
    GREEN: '&agreen'
    AQUA: '&baqua'
    RED: '&cred'
    LIGHT_PURPLE: '&dlight purple'
    YELLOW: '&eyellow'
    WHITE: '&fwhite'
  inv_lore:
    BLUE: '&9Change your ChatColor to blue'
    BLACK: '&0Change your ChatColor to black'
    DARK_BLUE: '&1Change your ChatColor to dark blue'
    DARK_GREEN: '&2Change your ChatColor to dark green'
    DARK_AQUA: '&3Change your ChatColor to dark aqua'
    DARK_RED: '&4Change your ChatColor to dark red'
    DARK_PURPLE: '&5Change your ChatColor to dark purple'
    GOLD: '&6Change your ChatColor to gold'
    GRAY: '&7Change your ChatColor to gray'
    DARK_GRAY: '&8Change your ChatColor to dark gray'
    GREEN: '&aChange your ChatColor to green'
    AQUA: '&bChange your ChatColor to aqua'
    RED: '&cChange your ChatColor to red'
    LIGHT_PURPLE: '&dChange your ChatColor to light purple'
    YELLOW: '&eChange your ChatColor to yellow'
    WHITE: '&fChange your ChatColor to white'
NameColorMessage:
  test: this is just a test
  Bla: another test
  noperm: '&cYou don''t have permissions to use this Command!'
  ColorInv: '&6Choose your NameColor:'
  color_changed:
    Normal: '&6You changed your NameColor to%colorID% %colorName% &6!'
    Mixed: '&6You changed your NameColor to%colorID% %colorName% &6mixed with %colorMixed%&6!'
  inv_title:
    BLUE: '&9blue'
    BLACK: '&0black'
    DARK_BLUE: '&1dark blue'
    DARK_GREEN: '&2dark green'
    DARK_AQUA: '&3dark aqua'
    DARK_RED: '&4dark red'
    DARK_PURPLE: '&5dark purple'
    GOLD: '&6gold'
    GRAY: '&7gray'
    DARK_GRAY: '&8dark gray'
    GREEN: '&agreen'
    AQUA: '&baqua'
    RED: '&cred'
    LIGHT_PURPLE: '&dlight purple'
    YELLOW: '&eyellow'
    WHITE: '&fwhite'
    rainbow: '&aR&ea&ci&1n&6b&do&4w'
  inv_lore:
    BLUE: '&9Change your NameColor to blue'
    BLACK: '&0Change your NameColor to black'
    DARK_BLUE: '&1Change your NameColor to dark blue'
    DARK_GREEN: '&2Change your NameColor to dark green'
    DARK_AQUA: '&3Change your NameColor to dark aqua'
    DARK_RED: '&4Change your NameColor to dark red'
    DARK_PURPLE: '&5Change your NameColor to dark purple'
    GOLD: '&6Change your NameColor to gold'
    GRAY: '&7Change your NameColor to gray'
    DARK_GRAY: '&8Change your NameColor to dark gray'
    GREEN: '&aChange your NameColor to green'
    AQUA: '&bChange your NameColor to aqua'
    RED: '&cChange your NameColor to red'
    LIGHT_PURPLE: '&dChange your NameColor to light purple'
    YELLOW: '&eChange your NameColor to yellow'
    WHITE: '&fChange your NameColor to white'
    rainbow: Change your NameColor to &aR&ea&ci&1n&6b&do&4w
TabColorMessage:
  test: this is just a test
  Bla: another test
  noperm: '&cYou don''t have permissions to use this Command!'
  ColorInv: '&6Choose your TabColor:'
  color_changed:
    Normal: '&6You changed your TabColor to%colorID% %colorName% &6!'
    Mixed: '&6You changed your TabColor to%colorID% %colorName% &6mixed with %colorMixed%&6!'
  inv_title:
    BLUE: '&9blue'
    BLACK: '&0black'
    DARK_BLUE: '&1dark blue'
    DARK_GREEN: '&2dark green'
    DARK_AQUA: '&3dark aqua'
    DARK_RED: '&4dark red'
    DARK_PURPLE: '&5dark purple'
    GOLD: '&6gold'
    GRAY: '&7gray'
    DARK_GRAY: '&8dark gray'
    GREEN: '&agreen'
    AQUA: '&baqua'
    RED: '&cred'
    LIGHT_PURPLE: '&dlight purple'
    YELLOW: '&eyellow'
    WHITE: '&fwhite'
    rainbow: '&aR&ea&ci&1n&6b&do&4w'
  inv_lore:
    BLUE: '&9Change your TabColor to blue'
    BLACK: '&0Change your TabColor to black'
    DARK_BLUE: '&1Change your TabColor to dark blue'
    DARK_GREEN: '&2Change your TabColor to dark green'
    DARK_AQUA: '&3Change your TabColor to dark aqua'
    DARK_RED: '&4Change your TabColor to dark red'
    DARK_PURPLE: '&5Change your TabColor to dark purple'
    GOLD: '&6Change your TabColor to gold'
    GRAY: '&7Change your TabColor to gray'
    DARK_GRAY: '&8Change your TabColor to dark gray'
    GREEN: '&aChange your TabColor to green'
    AQUA: '&bChange your TabColor to aqua'
    RED: '&cChange your TabColor to red'
    LIGHT_PURPLE: '&dChange your TabColor to light purple'
    YELLOW: '&eChange your TabColor to yellow'
    WHITE: '&fChange your TabColor to white'
    rainbow: Change your TabColor to &aR&ea&ci&1n&6b&do&4w
