TradeSystem:
  Prefix: '&6&lTRADE &8┃ &f'
  Language: ENG
  #Permissions:
  #   "tradesystem.trade": Can accept/deny/toggle trade requests
  #   "tradesystem.trade.initiate": Can invite players for trades
  #If permissions are disabled, every player is able to accept/deny/toggle/initiate trades
  Permissions: false

  # Both traders have to add an item/money to finish the trade
  Trade_Both: true
  Trade_with_money: true
  Trade_Distance:
    enabled: true
    distance_in_blocks: 10
  Allowed_GameModes:
  - SURVIVAL
  Blocked_Worlds:
  - ExampleWorld-1
  - ExampleWorld-2
  Blacklist:
  - '{"Material":"AIR","Data":0}'
  - '{"Displayname":"&cExample","Material":"AIR","Data":0}'
  - '{"Displayname":"&6&lKeystone &7&o(Right-click)"}'

  # true: After finishing a trade all items will be dropped, if the inventory is full
  # false: Prevent the tradepartner to put to much items into the gui
  Trade_Drop_Items: true

  # After 60 seconds the request will be expired
  Request_Cooldown_In_Sek: 30

  Action_To_Cancel:
    Player_get_damaged: true

  Action_To_Request:
    Rightclick: true
    # Shift-Rightclick
    Shiftclick: true

  # Sound names can be found here: https://github.com/CodingAir/CodingAPI/blob/CodingAir/src/de/codingair/codingapi/server/Sound.java
  # The name is here the first name in front of the '('. Example: AMBIENCE_CAVE in line 12: "(»)AMBIENCE_CAVE(«)("AMBIENCE_CAVE", "AMBIENT_CAVE"),"
  # Make sure that the names have the correct cases!
  Sounds:
    Trade_Started:
      Name: LEVEL_UP
      Volume: 0.6
      Pitch: 1.0
    Trade_Finished:
      Name: LEVEL_UP
      Volume: 0.6
      Pitch: 1.0
    Trade_Blocked:
      Name: NOTE_BASS
      Volume: 0.8
      Pitch: 0.6
    Trade_Cancelled:
      Name: ITEM_BREAK
      Volume: 0.6
      Pitch: 1.0
    Trade_Request:
      Name: ORB_PICKUP
      Volume: 0.6
      Pitch: 1.0
