# PlaceholderAPI
# Version: 2.10.2
# Created by: extended_clip
# Contributors: https://github.com/PlaceholderAPI/PlaceholderAPI/graphs/contributors
# Issues: https://github.com/PlaceholderAPI/PlaceholderAPI/issues
# Expansions: https://api.extendedclip.com/all/
# Wiki: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki
# Discord: https://helpch.at/discord
# No placeholders are provided with this plugin by default.
# Download placeholders: /papi ecloud
check_updates: false
cloud_enabled: true
cloud_allow_unverified_expansions: false
boolean:
  'true': 'yes'
  'false': 'no'
date_format: MM/dd/yy HH:mm:ss
expansions:
  vault:
    formatting:
      thousands: k
      trillions: T
      quadrillions: Q
      billions: B
      millions: M
  javascript:
    engine: javascript
  server:
    tps_color:
      high: '&a'
      low: '&c'
      medium: '&e'
    server_name: A Minecraft Server
  progress:
    in_progress: '&e■'
    length: 10
    completed: '&a■'
    maximum_value: 100
    remaining: '&7■'
    full: '&aCompleted'
  tokenmanager:
    check_interval: 30
  math:
    Precision: 0
    Debug: 'off'
