# DeluxeTags version: 1.8.1 Main Configuration
# 
# Create your tags using the following format:
# 
# deluxetags:
#   VIP: 
#     order: 1
#     tag: '&7[&eVIP&7]'
#     description: 'This tag is awarded by getting VIP'
# 
# Placeholders for your DeluxeChat formats config:
# 
# %deluxetags_identifier% - display the players active tag identifier
# %deluxetags_tag% - display the players active tag
# %deluxetags_description% - display the players active tag description
# %deluxetags_amount% - display the amount of tags a player has access to
# 
# Placeholders for your essentials/chat handling formats config:
# 
# {deluxetags_identifier} - display the players active tag identifier
# {deluxetags_tag} - display the players active tag
# {deluxetags_description} - display the players active tag description
# {deluxetags_amount} - display the amount of tags a player has access to
load_tag_on_join: true
force_tags: false
check_updates: true
deluxe_chat: true
format_chat:
  enabled: true
  format: '{deluxetags_tag} <%1$s> %2$s'
gui:
  name: '&6Available tags&f: &6%deluxetags_amount%'
  tag_select_item:
    material: NAME_TAG
    data: 0
    displayname: '&6Tag&f: &6%deluxetags_identifier%'
    lore:
    - '%deluxetags_tag%'
    - '%deluxetags_description%'
  divider_item:
    material: STAINED_GLASS_PANE
    data: 15
    displayname: ''
    lore: []
  has_tag_item:
    material: SKULL_ITEM
    data: 3
    displayname: '&eCurrent tag&f: &6%deluxetags_identifier%'
    lore:
    - '%deluxetags_tag%'
    - Click to remove your current tag
  no_tag_item:
    material: SKULL_ITEM
    data: 3
    displayname: '&cYou don''t have a tag set!'
    lore:
    - '&7Click a tag above to select one!'
  exit_item:
    material: IRON_DOOR
    data: 0
    displayname: '&cClick to exit'
    lore:
    - '&7Exit the tags menu'
deluxetags:
  flower:
    order: 1
    tag: ' &d❀ &8┃'
    description: '&cAwarded for using DeluxeTags!'
  arrow:
    order: 2
    tag: ' &b➳ &8┃'
    description: '&cAwarded for using DeluxeTags!'
  yingyang:
    order: 3
    tag: ' ☯ &8┃'
    description: '&cAwarded for using DeluxeTags!'
  heart:
    order: 4
    tag: ' &c❤ &8┃'
    description: '&cAwarded for using DeluxeTags!'
  toxic:
    order: 5
    tag: ' &e☢ &8┃'
    description: '&cAwarded for using DeluxeTags!'
  peace:
    order: 6
    tag: ' &d✌ &8┃'
    description: '&cAwarded for using DeluxeTags!'
  music:
    order: 7
    tag: ' &a♫ &8┃'
    description: '&cAwarded for using DeluxeTags!'
  scissors:
    order: 8
    tag: ' &3✂ &8┃'
    description: '&cAwarded for using DeluxeTags!'
  writing:
    order: 9
    tag: ' &a✍ &8┃'
    description: '&cAwarded for using DeluxeTags!'
  snowman:
    order: 10
    tag: ' &b☃ &8┃'
    description: '&cAwarded for using DeluxeTags!'
