Potions:
    Explosive:
      event_map:
        BlockBreakEvent: "MONITOR"
        TEBlockExplodeEvent: "MONITOR"
      price: 350
      max: 20
      # you can nominate the world, which prevents explosive	  
      invalid_in_world:
#        - plotworld
      # you can turn on automatic pickup.
      pickup: true
      # you can apply the identification of holding tool for pickup process.
      applytool: true
      # you can turn on automatic smelting
      smelt: false
      # you can turn on/off explostion sound/visual effects
      effect: false
      # you can turn on/off explostion sound effects
      sound: false
      # you can increase the number of exploded blocs with in a radius
      multiplier: 2
      # you can specify the radius whithin which explosion will occur.
      # it is not recommended to have a large radius. it may cause lag.
      radius: 1.50
      # You can set the occurrence of explosion.
      # random: randomly occur based on the level
      # always: explosion occur always.
      occurrence: 0.10
      # You can set the list of blocks exempt from explosiont.
      # use this list to avoid your crates being exploded.
      # AIR and BEDROCK are already exempted by defalt
      exemptions:
        - ENDER_CHEST
        - GLOWSTONE
        - LADDER
        - STONE_PLATE
      use_explode_event: true
      conflict_with:
        - Sphered
        - Tile
        - Disk
        - Excavation
      drop_naturally: false # drop blocks naturally if it's not picking p.

