Potions:
  Slicing:
    alias: "Jackhammer"
    event_map:
      BlockBreakEvent: "MONITOR"
      TEBlockExplodeEvent: "MONITOR"
    price: 650
    max: 15  # the level of Slicing will be used as the depth of explosion.
    # you can nominate the world, which prevents explosive
    invalid_in_world:
#      - plotworld
    # you can turn on automatic pickup.
    pickup: false
    # you can tunrn on automatic smelting
    smelt: false
    # you can turn on/off explostion sound/visual effects
    effect: false
    # you can turn on/off explostion sound effects
    sound: false
    # You can set the occurrence of explosion.
    # random: randomly occur based on the level
    # always: explosion occur always.
    occurrence: 0.10
    use_explode_event: true # use efficient explode event.
    use_level_as_depth: false  #use the level of enchant to decide the depth of slicing.
    cooldown: 15  # inseconds
    cooldown_message: "" #"&a[TE] You have to wait for &b%remaining% &aseconds."
    maxRadius: 100  #in case you miss config your mine.
    drop_naturally: false # drop blocks naturally if it's not picking p.
    # You can set the list of blocks exempt from explosiont.
    # use this list to avoid your crates being exploded.
    # AIR and BEDROCK are already exempted by defalt
    exemptions:
      - ENDER_CHEST
      - GLOWSTONE
      - LADDER
      - STONE_PLATE
